version: '3.8'

services:
  # gitlab:
  #   image: 'gitlab/gitlab-ee:15.8.1-ce.0'
  #   restart: always
  #   hostname: 'gitlab.internal.domain'
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'https://gitlab.internal.domain'
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   # ports:
  #   #   - '80:80'
  #   #   - '443:443'
  #   #   - '22:22'
  #   volumes:
  #     - 'gitlab-config:/config:/etc/gitlab'
  #     - 'gitlab-logs/logs:/var/log/gitlab'
  #     - 'gitlab-data/data:/var/opt/gitlab'
  #   shm_size: '256m'


  jenkins:
    image: jenkins/jenkins:2.389-jdk11
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    #   - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home

  nexus:
    image: sonatype/nexus3:3.46.0
    restart: unless-stopped
    volumes:
      - nexus-data:/nexus-data
    #  ports:
    #  - 8081:8081

  nginx:
    image: nginx:1.22.1
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - nexus
      - jenkins
      # - gitlab

      # secrets:
      #   mysql_root_password:
      #     file: mysql_root_passwd.txt

volumes:
  gitlab-config: {}
  gitlab-logs: {}
  gitlab-data: {}
  jenkins-data: {}
  nexus-data: {}
